// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockShortLinkRepository creates a new instance of MockShortLinkRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShortLinkRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShortLinkRepository {
	mock := &MockShortLinkRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockShortLinkRepository is an autogenerated mock type for the ShortLinkRepository type
type MockShortLinkRepository struct {
	mock.Mock
}

type MockShortLinkRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockShortLinkRepository) EXPECT() *MockShortLinkRepository_Expecter {
	return &MockShortLinkRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockShortLinkRepository
func (_mock *MockShortLinkRepository) Get(id string) (string, bool) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (string, bool)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockShortLinkRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockShortLinkRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - id string
func (_e *MockShortLinkRepository_Expecter) Get(id any) *MockShortLinkRepository_Get_Call {
	return &MockShortLinkRepository_Get_Call{Call: _e.mock.On("Get", id)}
}

func (_c *MockShortLinkRepository_Get_Call) Run(run func(id string)) *MockShortLinkRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockShortLinkRepository_Get_Call) Return(s string, b bool) *MockShortLinkRepository_Get_Call {
	_c.Call.Return(s, b)
	return _c
}

func (_c *MockShortLinkRepository_Get_Call) RunAndReturn(run func(id string) (string, bool)) *MockShortLinkRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockShortLinkRepository
func (_mock *MockShortLinkRepository) Save(id string, originalURL string) bool {
	ret := _mock.Called(id, originalURL)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = returnFunc(id, originalURL)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockShortLinkRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockShortLinkRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - id string
//   - originalURL string
func (_e *MockShortLinkRepository_Expecter) Save(id any, originalURL any) *MockShortLinkRepository_Save_Call {
	return &MockShortLinkRepository_Save_Call{Call: _e.mock.On("Save", id, originalURL)}
}

func (_c *MockShortLinkRepository_Save_Call) Run(run func(id string, originalURL string)) *MockShortLinkRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShortLinkRepository_Save_Call) Return(b bool) *MockShortLinkRepository_Save_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockShortLinkRepository_Save_Call) RunAndReturn(run func(id string, originalURL string) bool) *MockShortLinkRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
