// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlers

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockShortLinkService creates a new instance of MockShortLinkService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShortLinkService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShortLinkService {
	mock := &MockShortLinkService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockShortLinkService is an autogenerated mock type for the ShortLinkService type
type MockShortLinkService struct {
	mock.Mock
}

type MockShortLinkService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockShortLinkService) EXPECT() *MockShortLinkService_Expecter {
	return &MockShortLinkService_Expecter{mock: &_m.Mock}
}

// CreateShortLink provides a mock function for the type MockShortLinkService
func (_mock *MockShortLinkService) CreateShortLink(ctx context.Context, originalURL string) (string, error) {
	ret := _mock.Called(ctx, originalURL)

	if len(ret) == 0 {
		panic("no return value specified for CreateShortLink")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, originalURL)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, originalURL)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, originalURL)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShortLinkService_CreateShortLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateShortLink'
type MockShortLinkService_CreateShortLink_Call struct {
	*mock.Call
}

// CreateShortLink is a helper method to define mock.On call
//   - ctx context.Context
//   - originalURL string
func (_e *MockShortLinkService_Expecter) CreateShortLink(ctx any, originalURL any) *MockShortLinkService_CreateShortLink_Call {
	return &MockShortLinkService_CreateShortLink_Call{Call: _e.mock.On("CreateShortLink", ctx, originalURL)}
}

func (_c *MockShortLinkService_CreateShortLink_Call) Run(run func(ctx context.Context, originalURL string)) *MockShortLinkService_CreateShortLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShortLinkService_CreateShortLink_Call) Return(s string, err error) *MockShortLinkService_CreateShortLink_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockShortLinkService_CreateShortLink_Call) RunAndReturn(run func(ctx context.Context, originalURL string) (string, error)) *MockShortLinkService_CreateShortLink_Call {
	_c.Call.Return(run)
	return _c
}

// GetSourceLink provides a mock function for the type MockShortLinkService
func (_mock *MockShortLinkService) GetSourceLink(ctx context.Context, id string) (string, bool, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSourceLink")
	}

	var r0 string
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, bool, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, id)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockShortLinkService_GetSourceLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSourceLink'
type MockShortLinkService_GetSourceLink_Call struct {
	*mock.Call
}

// GetSourceLink is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockShortLinkService_Expecter) GetSourceLink(ctx any, id any) *MockShortLinkService_GetSourceLink_Call {
	return &MockShortLinkService_GetSourceLink_Call{Call: _e.mock.On("GetSourceLink", ctx, id)}
}

func (_c *MockShortLinkService_GetSourceLink_Call) Run(run func(ctx context.Context, id string)) *MockShortLinkService_GetSourceLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShortLinkService_GetSourceLink_Call) Return(s string, b bool, err error) *MockShortLinkService_GetSourceLink_Call {
	_c.Call.Return(s, b, err)
	return _c
}

func (_c *MockShortLinkService_GetSourceLink_Call) RunAndReturn(run func(ctx context.Context, id string) (string, bool, error)) *MockShortLinkService_GetSourceLink_Call {
	_c.Call.Return(run)
	return _c
}
